package server.model.message;

public enum MessageType {
    AUTHORIZATION,
    EMPLOYEE_LIST,SAVE_NEW_EMPLOYEE,DELETE_EMPLOYEES,EDIT_EMPLOYEE,SEND_EMPLOYEE,
    ALL_INSTITUTION_LIST,DELETE_INSTITUTIONS,SAVE_NEW_INSTITUTION,EDIT_INSTITUTION,SEND_INSTITUTION,
    SEND_EMPLOYEE_DISTRIBUTOR,EDIT_EMPLOYEE_DISTRIBUTOR, SEND_FOR_LOCALIZATION_FOR_NOTIFICATION, SEND_FOR_INSTITUTION_FOR_LOCALIZATION,
    SAVE_NEW_FIRST_NOTIFICATION, SAVE_NEW_SECOND_NOTIFICATION, SEND_NOTIFICATION
}
